name: Build APK

on:
  workflow_dispatch:  # 允许手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 下载代码
      uses: actions/checkout@v3
    
    - name: 设置 Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    
    - name: 构建 APK
      run: |
        chmod +x gradlew
        ./gradlew :application:app:assembleDebug
    
    - name: 上传 APK
      uses: actions/upload-artifact@v3
      with:
        name: vlc-apk
        path: application/app/build/outputs/apk/debug/*.apk
